### ISSUE TITLE
Metadata Caption

### ISSUE THREAD

**Issue by ZoneX95** [Cknight70/twitter-image-bot#5]
Hey it is me again, I got it to work howvr I got one more issue. Is it possible to make the bot use same caption for everything it posts? Adding it for each individual filename would take a year haha.

**Comment by Cknight70** [comment]
Try replacing `status: caption,` on line 56 of server.js with the text you want to be posted in single quotes ' ' so for example `status: 'a new post!',`

Let me know if it works, I will update the readme.

**Comment by ZoneX95** [comment]
Yep works fine, tested many times. Only have to keep it in single line or it will break. Thanks man this is officialy the most easy to set up twitterbot on github.

**Comment by Cknight70** [comment]
Glad to hear it!
